services:
  api:
    build: .
    volumes:
      - /usr/src/app
    ports:
      - '3001:3000'
    command: npm run start:dev
    networks:
      - framedata_network
    restart: always
    expose:
      - 3000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tekken-framedata
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - framedata_network
    restart: always

networks:
  framedata_network:
    external: true

volumes:
  mongodb_data:
